# Each subprocess retains its own initialization and failure boundary. A failed
# check must not prevent later checks from running or hide their diagnostics.
set(fuelsim_internal_completed 0)
set(fuelsim_internal_failures)

function(fuelsim_run_internal_check name timeout)
    message(STATUS "Internal check BEGIN: ${name}")
    execute_process(COMMAND ${ARGN} RESULT_VARIABLE result TIMEOUT "${timeout}")
    math(EXPR completed "${fuelsim_internal_completed} + 1")
    set(fuelsim_internal_completed "${completed}" PARENT_SCOPE)
    if(NOT "${result}" STREQUAL "0")
        message(STATUS "Internal check FAIL: ${name}: ${result}")
        set(fuelsim_internal_failures ${fuelsim_internal_failures} "${name}" PARENT_SCOPE)
    else()
        message(STATUS "Internal check PASS: ${name}")
    endif()
endfunction()

function(fuelsim_finish_internal_checks expected)
    if(NOT fuelsim_internal_completed EQUAL expected)
        message(FATAL_ERROR "Internal check count mismatch: ${fuelsim_internal_completed}/${expected}")
    endif()
    if(fuelsim_internal_failures)
        message(FATAL_ERROR "Failed internal checks: ${fuelsim_internal_failures}")
    endif()
    message(STATUS "All ${expected} internal checks passed")
endfunction()
