cmake_minimum_required(VERSION 3.20)
# This is a direct-include and source-ownership check, not a C++ semantic parser.
if(NOT DEFINED ELEMENTS_SOURCE_DIR)
    get_filename_component(ELEMENTS_SOURCE_DIR "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
endif()
set(detail "${ELEMENTS_SOURCE_DIR}/src/detail")
file(GLOB private_headers RELATIVE "${detail}" "${detail}/*.hpp")
file(GLOB private_files "${detail}/*.hpp" "${detail}/*.cpp")

foreach(path IN LISTS private_files)
    get_filename_component(name "${path}" NAME)
    get_filename_component(stem "${path}" NAME_WE)
    set(allowed "${stem}.hpp")
    if(stem MATCHES "^(cax4|cax8|c3d8|c3d20|line2_rz)_geometry$")
        list(APPEND allowed matrix3.hpp)
    elseif(stem MATCHES "^(cax8|c3d8|c3d20|cartesian)_kinematics$")
        list(APPEND allowed cartesian_kinematics.hpp matrix3.hpp)
    elseif(stem MATCHES "^(cax8|c3d20)_assembly$")
        list(APPEND allowed "${CMAKE_MATCH_1}_kinematics.hpp" cartesian_material.hpp ad_local_system.hpp matrix3.hpp)
    elseif(stem STREQUAL "c3d8_diagnostics")
        list(APPEND allowed c3d8_geometry.hpp c3d8_kinematics.hpp)
    elseif(stem STREQUAL "cartesian_material")
        list(APPEND allowed matrix3.hpp)
    elseif(stem STREQUAL "line2_rz_local_system")
        list(APPEND allowed ad_local_system.hpp)
    elseif(NOT stem MATCHES "^(matrix3|ad_local_system)$")
        message(FATAL_ERROR "Unclassified private file: ${name}; define its responsibility first")
    endif()
    file(READ "${path}" content)
    string(REGEX MATCHALL "#[ \t]*include[ \t]*[<\"][^>\"\n]+[>\"]" includes "${content}")
    foreach(include IN LISTS includes)
        string(REGEX REPLACE ".*[<\"]([^>\"]+)[>\"]" "\\1" target "${include}")
        get_filename_component(target_name "${target}" NAME)
        if(target_name IN_LIST private_headers AND NOT target_name IN_LIST allowed)
            message(FATAL_ERROR "Forbidden private dependency: ${name} -> ${target}")
        endif()
        if(target_name MATCHES "^(material|material_functions)\\.hpp$" AND stem MATCHES "(_geometry|_kinematics|_diagnostics|matrix3)$")
            message(FATAL_ERROR "Material dependency in geometry/kinematics/diagnostics: ${name}")
        endif()
    endforeach()
    if(stem MATCHES "(_geometry|_kinematics|_diagnostics|matrix3)$" AND
       content MATCHES "IsotropicThermoelasticMaterial|MaterialFunctionContext|evaluate_stress_tangent|[.]material[.]|[.]incremental_response[(]|[.]response[(]")
        message(FATAL_ERROR "Material computation in geometry/kinematics/diagnostics: ${name}")
    endif()
    if(stem MATCHES "_assembly$" AND content MATCHES "struct[ \t\n]+[A-Za-z0-9_]*Kinematics")
        message(FATAL_ERROR "Kinematics type belongs in the kinematics module: ${name}")
    endif()
endforeach()

# Consumers must use public headers. Restrict traversal to source directories so
# build trees and generated third-party files are not scanned.
file(GLOB_RECURSE consumers
    "${ELEMENTS_SOURCE_DIR}/include/*.hpp"
    "${ELEMENTS_SOURCE_DIR}/tests/*.hpp" "${ELEMENTS_SOURCE_DIR}/tests/*.cpp")
if(DEFINED FUELSIM_SOURCE_DIR AND NOT FUELSIM_SOURCE_DIR STREQUAL ELEMENTS_SOURCE_DIR)
    foreach(directory include src tests benchmarks)
        file(GLOB_RECURSE host_files "${FUELSIM_SOURCE_DIR}/${directory}/*.hpp" "${FUELSIM_SOURCE_DIR}/${directory}/*.cpp")
        list(APPEND consumers ${host_files})
    endforeach()
endif()
foreach(path IN LISTS consumers)
    file(READ "${path}" content)
    string(REGEX MATCHALL "#[ \t]*include[ \t]*[<\"][^>\"\n]+[>\"]" includes "${content}")
    foreach(include IN LISTS includes)
        string(REGEX REPLACE ".*[<\"]([^>\"]+)[>\"]" "\\1" target "${include}")
        get_filename_component(target_name "${target}" NAME)
        if(target_name IN_LIST private_headers)
            message(FATAL_ERROR "Private element header used by public consumer: ${path} -> ${target}")
        endif()
    endforeach()
endforeach()
message(STATUS "Element private dependency and responsibility checks passed")
