cmake_minimum_required(VERSION 3.20)
if(NOT DEFINED ELEMENTS_SOURCE_DIR)
    get_filename_component(ELEMENTS_SOURCE_DIR "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
endif()
if(EXISTS "${ELEMENTS_SOURCE_DIR}/src/detail")
    message(FATAL_ERROR "Element implementations must be flat; src/detail must not exist")
endif()
file(GLOB public_headers "${ELEMENTS_SOURCE_DIR}/include/*.hpp")
file(GLOB private_headers RELATIVE "${ELEMENTS_SOURCE_DIR}/src" "${ELEMENTS_SOURCE_DIR}/src/*.hpp")
set(models cax4t cax4rt cax8t cax8rt c3d8t c3d8rt c3d20t c3d20rt)
set(interfaces line2_rz line3_rz quad4_face quad8_face)
foreach(model IN LISTS models interfaces)
    foreach(path "include/${model}.hpp" "src/${model}.cpp" "tests/${model}_tests.cpp")
        if(NOT EXISTS "${ELEMENTS_SOURCE_DIR}/${path}")
            message(FATAL_ERROR "Missing type-owned interface, implementation or test: ${path}")
        endif()
    endforeach()
endforeach()
file(GLOB source_files "${ELEMENTS_SOURCE_DIR}/src/*.cpp" "${ELEMENTS_SOURCE_DIR}/src/*.hpp")
foreach(path IN LISTS source_files public_headers)
    file(READ "${path}" content)
    if(content MATCHES "diagnose_c3d8|C3d8Diagnostics|C3d8PointDiagnostics")
        message(FATAL_ERROR "The separate C3D8 diagnostic API must not return: ${path}")
    endif()
    if(content MATCHES "#[ \t]*include[ \t]*[<\"][^>\"]*(support/|tests/|detail/)")
        message(FATAL_ERROR "Production code includes test support or an obsolete detail path: ${path}")
    endif()
    get_filename_component(stem "${path}" NAME_WE)
    if(stem MATCHES "^line[23]_rz$" AND content MATCHES "#[ \t]*include[ \t]*[<\"]quad[48]_face[.]hpp")
        message(FATAL_ERROR "Axisymmetric interfaces must use shared types, not three-dimensional face interfaces: ${path}")
    endif()
    if(stem IN_LIST models)
        foreach(other IN LISTS models)
            if(NOT other STREQUAL stem AND content MATCHES "evaluate_${other}[ \t\n]*[(]")
                message(FATAL_ERROR "One element model calls another: ${stem} -> ${other}")
            endif()
        endforeach()
    endif()
endforeach()
file(GLOB_RECURSE consumers "${ELEMENTS_SOURCE_DIR}/tests/*.cpp" "${ELEMENTS_SOURCE_DIR}/tests/*.hpp")
list(APPEND consumers ${public_headers})
if(DEFINED FUELSIM_SOURCE_DIR AND NOT FUELSIM_SOURCE_DIR STREQUAL ELEMENTS_SOURCE_DIR)
    foreach(directory include src tests benchmarks)
        file(GLOB_RECURSE files "${FUELSIM_SOURCE_DIR}/${directory}/*.cpp" "${FUELSIM_SOURCE_DIR}/${directory}/*.hpp")
        list(APPEND consumers ${files})
    endforeach()
endif()
foreach(path IN LISTS consumers)
    file(READ "${path}" content)
    string(REGEX MATCHALL "#[ \t]*include[ \t]*[<\"][^>\"\n]+[>\"]" includes "${content}")
    foreach(include IN LISTS includes)
        string(REGEX REPLACE ".*[<\"]([^>\"]+)[>\"]" "\\1" target "${include}")
        get_filename_component(name "${target}" NAME)
        if(name IN_LIST private_headers)
            message(FATAL_ERROR "A public consumer includes a private element header: ${path} -> ${target}")
        endif()
    endforeach()
endforeach()
message(STATUS "Element type ownership and private-interface checks passed")
