cmake_minimum_required(VERSION 3.20)
if(NOT DEFINED ELEMENTS_SOURCE_DIR)
    get_filename_component(ELEMENTS_SOURCE_DIR "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
endif()
if(EXISTS "${ELEMENTS_SOURCE_DIR}/src/detail")
    message(FATAL_ERROR "Element implementations must be flat; src/detail must not exist")
endif()
file(GLOB public_headers "${ELEMENTS_SOURCE_DIR}/include/*.hpp")
file(GLOB private_headers RELATIVE "${ELEMENTS_SOURCE_DIR}/src" "${ELEMENTS_SOURCE_DIR}/src/*.hpp")
set(models cax4t cax4rt cax8t cax8rt c3d8t c3d8rt c3d20t c3d20rt)
set(interfaces line2_rz line3_rz quad4_face quad8_face)
foreach(model IN LISTS models interfaces)
    foreach(path "include/${model}.hpp" "src/${model}.cpp" "tests/${model}_tests.cpp")
        if(NOT EXISTS "${ELEMENTS_SOURCE_DIR}/${path}")
            message(FATAL_ERROR "Missing type-owned interface, implementation or test: ${path}")
        endif()
    endforeach()
endforeach()
file(GLOB source_files "${ELEMENTS_SOURCE_DIR}/src/*.cpp" "${ELEMENTS_SOURCE_DIR}/src/*.hpp")
foreach(path IN LISTS source_files public_headers)
    file(READ "${path}" content)
    if(content MATCHES "diagnose_c3d8|C3d8Diagnostics|C3d8PointDiagnostics")
        message(FATAL_ERROR "The separate C3D8 diagnostic API must not return: ${path}")
    endif()
    if(content MATCHES "#[ \t]*include[ \t]*[<\"][^>\"]*(support/|tests/|detail/)")
        message(FATAL_ERROR "Production code includes test support or an obsolete detail path: ${path}")
    endif()
    get_filename_component(stem "${path}" NAME_WE)
    string(REGEX MATCHALL "template[ \t\r\n]*<" templates "${content}")
    list(LENGTH templates template_count)
    if(template_count GREATER 0)
        set(allowed_templates)
        if(path STREQUAL "${ELEMENTS_SOURCE_DIR}/src/c3d_common.hpp")
            set(allowed_templates hughes_winget_rotation)
        elseif(path STREQUAL "${ELEMENTS_SOURCE_DIR}/src/c3d_common.cpp")
            set(allowed_templates determinant_impl inverse_impl multiply_impl central_increment_gradient_impl reduced_hex8_metric_impl hex8_hourglass_shape_impl reduced_hex8_thermal_hourglass_coefficients_impl)
        elseif(path STREQUAL "${ELEMENTS_SOURCE_DIR}/src/quad8_face.cpp")
            set(allowed_templates quad8_shape_impl)
        elseif(path STREQUAL "${ELEMENTS_SOURCE_DIR}/src/material.cpp")
            set(allowed_templates rotate_cartesian_tensor_impl)
        endif()
        list(LENGTH allowed_templates allowed_count)
        if(NOT template_count EQUAL allowed_count)
            message(FATAL_ERROR "Only explicitly listed private mathematical templates are permitted: ${path}")
        endif()
        foreach(name IN LISTS allowed_templates)
            if(NOT content MATCHES "template[ \t\r\n]*<typename Scalar>[ \t\r\n]*(Scalar|void|std::array<Scalar, [46]>|std::array<std::array<Scalar, 3>, 3>|std::array<std::array<Scalar, 4>, 8>)[ \t\r\n]+${name}[(]")
                message(FATAL_ERROR "Unexpected mathematical template declaration: ${path} -> ${name}")
            endif()
        endforeach()
    endif()
    if(stem MATCHES "^material(_types|_functions)?$")
        string(REGEX MATCHALL "#[ \t]*include[ \t]*[<\"][^>\"\n]+[>\"]" material_includes "${content}")
        foreach(include IN LISTS material_includes)
            string(REGEX REPLACE ".*[<\"]([^>\"]+)[>\"]" "\\1" target "${include}")
            get_filename_component(name "${target}" NAME_WE)
            if(name IN_LIST models OR name IN_LIST interfaces OR name MATCHES "^(cax|c3d).*_(common|types)$")
                message(FATAL_ERROR "Material code must not depend on element models or interfaces: ${path} -> ${target}")
            endif()
        endforeach()
    endif()
    if(stem MATCHES "^line[23]_rz$" AND content MATCHES "#[ \t]*include[ \t]*[<\"]quad[48]_face[.]hpp")
        message(FATAL_ERROR "Axisymmetric interfaces must use shared types, not three-dimensional face interfaces: ${path}")
    endif()
    if(stem IN_LIST models)
        foreach(other IN LISTS models)
            if((stem STREQUAL "cax8rt" AND other STREQUAL "cax8t") OR
               (stem STREQUAL "c3d20rt" AND other STREQUAL "c3d20t"))
                continue()
            endif()
            if(NOT other STREQUAL stem AND
               (content MATCHES "(evaluate_${other}|make_${other}_geometry|validate_${other}_deformation)[ \t\n]*[(]" OR
                content MATCHES "#[ \t]*include[ \t]*[<\"]${other}[.]hpp"))
                message(FATAL_ERROR "One element model calls another: ${stem} -> ${other}")
            endif()
        endforeach()
    endif()
endforeach()
file(GLOB_RECURSE consumers "${ELEMENTS_SOURCE_DIR}/tests/*.cpp" "${ELEMENTS_SOURCE_DIR}/tests/*.hpp")
list(APPEND consumers ${public_headers})
if(DEFINED FUELSIM_SOURCE_DIR AND NOT FUELSIM_SOURCE_DIR STREQUAL ELEMENTS_SOURCE_DIR)
    foreach(directory include src tests benchmarks)
        file(GLOB_RECURSE files "${FUELSIM_SOURCE_DIR}/${directory}/*.cpp" "${FUELSIM_SOURCE_DIR}/${directory}/*.hpp")
        list(APPEND consumers ${files})
    endforeach()
endif()
foreach(path IN LISTS consumers)
    file(READ "${path}" content)
    string(REGEX MATCHALL "#[ \t]*include[ \t]*[<\"][^>\"\n]+[>\"]" includes "${content}")
    foreach(include IN LISTS includes)
        string(REGEX REPLACE ".*[<\"]([^>\"]+)[>\"]" "\\1" target "${include}")
        get_filename_component(name "${target}" NAME)
        if(name IN_LIST private_headers AND NOT
            ((path STREQUAL "${ELEMENTS_SOURCE_DIR}/tests/contact_common_tests.cpp" AND name STREQUAL "contact_common.hpp") OR
             (path STREQUAL "${ELEMENTS_SOURCE_DIR}/tests/common_math_tests.cpp" AND name MATCHES "^((cax|c3d)_common|quad8_shape)[.]hpp$")))
            message(FATAL_ERROR "A public consumer includes a private element header: ${path} -> ${target}")
        endif()
    endforeach()
endforeach()
message(STATUS "Element type ownership and private-interface checks passed")
