# Group scheduling metadata only; never generate or modify physical input cards.
function(fuelsim_add_internal_check group)
    cmake_parse_arguments(PARSE_ARGV 1 check "" "NAME" "COMMAND")
    if(NOT group MATCHES "^(rz|hex8|hex20)$" OR NOT check_NAME OR NOT check_COMMAND
       OR check_UNPARSED_ARGUMENTS)
        message(FATAL_ERROR "Invalid internal check registration")
    endif()
    get_property(existing GLOBAL PROPERTY "fuelsim_check_${check_NAME}_group")
    if(existing)
        message(FATAL_ERROR "Duplicate internal check: ${check_NAME}")
    endif()
    set_property(GLOBAL PROPERTY "fuelsim_check_${check_NAME}_group" "${group}")
    set_property(GLOBAL APPEND PROPERTY "fuelsim_${group}_checks" "${check_NAME}")
    list(POP_FRONT check_COMMAND target)
    if(NOT TARGET "${target}")
        message(FATAL_ERROR "Internal check must use an existing executable target: ${target}")
    endif()
    set(command "\"$<TARGET_FILE:${target}>\"")
    foreach(argument IN LISTS check_COMMAND)
        if(argument MATCHES "\\]===\\]")
            message(FATAL_ERROR "Unsupported internal check argument delimiter")
        endif()
        string(APPEND command " [===[${argument}]===]")
    endforeach()
    set_property(GLOBAL PROPERTY "fuelsim_check_${check_NAME}_command" "${command}")
endfunction()

function(fuelsim_set_internal_properties)
    set(names)
    set(index 0)
    while(index LESS ARGC)
        if(ARGV${index} STREQUAL "PROPERTIES")
            math(EXPR index "${index} + 1")
            break()
        endif()
        list(APPEND names "${ARGV${index}}")
        math(EXPR index "${index} + 1")
    endwhile()
    while(index LESS ARGC)
        set(key "${ARGV${index}}")
        math(EXPR index "${index} + 1")
        if(NOT key MATCHES "^(LABELS|FIXTURES_REQUIRED|TIMEOUT)$" OR NOT index LESS ARGC)
            message(FATAL_ERROR "Unsupported internal check property: ${key}")
        endif()
        foreach(name IN LISTS names)
            get_property(group GLOBAL PROPERTY "fuelsim_check_${name}_group")
            if(NOT group)
                message(FATAL_ERROR "Unknown internal check: ${name}")
            endif()
            set_property(GLOBAL PROPERTY "fuelsim_check_${name}_${key}" "${ARGV${index}}")
        endforeach()
        math(EXPR index "${index} + 1")
    endwhile()
endfunction()

function(fuelsim_register_internal_groups)
    set(mapping "group\tcheck\n")
    foreach(group IN ITEMS rz hex8 hex20)
        get_property(checks GLOBAL PROPERTY "fuelsim_${group}_checks")
        set(script "include(\"${PROJECT_SOURCE_DIR}/tests/run_internal_checks.cmake\")\n")
        set(fixtures)
        set(labels internal unit "${group}")
        foreach(name IN LISTS checks)
            foreach(key IN ITEMS command LABELS FIXTURES_REQUIRED TIMEOUT)
                get_property(${key} GLOBAL PROPERTY "fuelsim_check_${name}_${key}")
            endforeach()
            list(APPEND fixtures ${FIXTURES_REQUIRED})
            list(APPEND labels ${LABELS})
            if(NOT TIMEOUT)
                set(TIMEOUT 120)
            endif()
            string(APPEND script "fuelsim_run_internal_check(${name} ${TIMEOUT} ${command})\n")
            string(APPEND mapping "fuelsim_internal_${group}_tests\t${name}\n")
        endforeach()
        list(LENGTH checks count)
        string(APPEND script "fuelsim_finish_internal_checks(${count})\n")
        set(path "${CMAKE_CURRENT_BINARY_DIR}/internal_checks/${group}-$<CONFIG>.cmake")
        file(GENERATE OUTPUT "${path}" CONTENT "${script}")
        add_test(NAME "fuelsim_internal_${group}_tests" COMMAND "${CMAKE_COMMAND}" -P "${path}")
        list(REMOVE_DUPLICATES labels)
        list(REMOVE_DUPLICATES fixtures)
        set_tests_properties("fuelsim_internal_${group}_tests" PROPERTIES
            LABELS "${labels}" FIXTURES_REQUIRED "${fixtures}")
    endforeach()
    file(GENERATE OUTPUT "${CMAKE_CURRENT_BINARY_DIR}/internal_checks/membership.tsv" CONTENT "${mapping}")
endfunction()
