if(NOT DEFINED ROOT OR NOT DEFINED MANIFEST)
    message(FATAL_ERROR "ROOT and MANIFEST are required")
endif()

file(STRINGS "${MANIFEST}" entries)
foreach(entry IN LISTS entries)
    if(NOT entry MATCHES "^([0-9a-f]+)  ([A-Za-z0-9_.-]+(/[A-Za-z0-9_.-]+)*)$")
        message(FATAL_ERROR "Invalid SHA256 manifest entry: ${entry}")
    endif()
    set(expected "${CMAKE_MATCH_1}")
    set(name "${CMAKE_MATCH_2}")
    if(name MATCHES [[(^|/)\.\.(/|$)]])
        message(FATAL_ERROR "Parent path is not allowed in reference manifest: ${name}")
    endif()
    string(LENGTH "${expected}" hash_length)
    if(NOT hash_length EQUAL 64)
        message(FATAL_ERROR "Invalid SHA256 length for ${name}")
    endif()
    set(path "${ROOT}/${name}")
    if(NOT EXISTS "${path}")
        message(FATAL_ERROR "Missing reference artifact: ${name}")
    endif()
    file(SHA256 "${path}" actual)
    if(NOT actual STREQUAL expected)
        message(FATAL_ERROR "SHA256 mismatch for ${name}: ${actual}")
    endif()
endforeach()

list(LENGTH entries count)
message(STATUS "Verified ${count} reference SHA256 entries")
